### ISSUE TITLE
Vehicles Not Attaching Properly

### ISSUE THREAD

**Issue by SouthSideRole** [Chip-W/cw_tow#1]
It seems like the script used bones of vehicles to attach them. Which in turn alot of vehicles will no clip through the floor of the trailer. Is there somewhere in the lua's i can change the coords or is it a automatic function?? I checked but couldnt seem to find any. Which is why i think its a automatic function since all cars attach diffrently??
![Screenshot 2022-10-19 114453](https://user-images.githubusercontent.com/116207065/196777579-b9d1317a-b956-4a3a-9956-093083a25765.png)

**Comment by Chip-W** [comment]
You can edit it as you wish. This is a pretty old basic script.

In the client, look for "AttachEntityToEntity".  These are the settings for where a vehicle sits.  However, every vehicle is different, so it's hard to get a perfect result.  By every vehicle, I include trailers in that as well.  If I remember correctly, I set this up with the PJ Trailer found on GTA 5 Mods website.

Anyway, to get the settings you need for that native, see this page:

https://docs.fivem.net/natives/?_0x6B9BBD38AB0796DF
